# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{techincaldebt}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Herring", "Jeremy Grant", "Gareth Stokes", "Carl Woodward"]
  s.date = %q{2009-08-24}
  s.description = %q{Gem to push details of technical debt to technicaldebt.us}
  s.email = %q{technicaldebt@gmail.com}
  s.executables = ["debtify", "senddebt"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/debtify",
     "bin/senddebt",
     "lib/technical_debt.rb",
     "spec/git_diffs.rb",
     "spec/spec_helper.rb",
     "spec/technical_debt_spec.rb",
     "techincaldebt.gemspec"
  ]
  s.homepage = %q{http://github.com/techincaldebt/technical_debt}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Gem to push details of technical debt to technicaldebt.us}
  s.test_files = [
    "spec/git_diffs.rb",
     "spec/spec_helper.rb",
     "spec/technical_debt_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end
